### ISSUE TITLE
pnpm install fails installing the explorer

### ISSUE THREAD

**Issue by HoTandy** [FuelLabs/fuel-explorer#222]
ProductName: macOS
ProductVersion: 14.3.1
BuildVersion: 23D60

```
npm version                              
{
  'fuel-explorer-project': '0.0.0',
  npm: '10.2.4',
  node: '20.11.1',
  acorn: '8.11.2',
  ada: '2.7.4',
  ares: '1.20.1',
  base64: '0.5.1',
  brotli: '1.0.9',
  cjs_module_lexer: '1.2.2',
  cldr: '43.1',
  icu: '73.2',
  llhttp: '8.1.1',
  modules: '115',
  napi: '9',
  nghttp2: '1.58.0',
  nghttp3: '0.7.0',
  ngtcp2: '0.8.1',
  openssl: '3.0.13+quic',
  simdutf: '4.0.4',
  tz: '2023c',
  undici: '5.28.3',
  unicode: '15.0',
  uv: '1.46.0',
  uvwasi: '0.0.19',
  v8: '11.3.244.8-node.17',
  zlib: '1.2.13.1-motley-5daffc7'
}

docker-compose version
Docker Compose version v2.24.6-desktop.1

rustup --version
rustup 1.26.0 (5af9b9484 2023-04-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.76.0 (07dca489a 2024-02-04)`

forc 0.46.1
```

Going through the Getting Started guide [https://github.com/FuelLabs/fuel-explorer/blob/main/docs/explorer/GETTING_STARTED.md](https://github.com/FuelLabs/fuel-explorer/blob/main/docs/explorer/GETTING_STARTED.md) for `fuel-explorer`, when I execute `pnpm install` under `Install Dependencies`, eventually I get the following error:

```
Scope: all 12 workspace projects
Lockfile is up to date, resolution step is skipped
Packages: +2624
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Downloading registry.npmjs.org/fuels/0.74.0: 5.76 MB/5.76 MB, done
Downloading registry.npmjs.org/typescript/5.3.3: 5.76 MB/5.76 MB, done
Downloading registry.npmjs.org/@swc/core-darwin-x64/1.4.0: 14.57 MB/14.57 MB, done
Downloading registry.npmjs.org/@tabler/icons/2.46.0: 5.55 MB/5.55 MB, done
Downloading registry.npmjs.org/next/14.1.0: 20.76 MB/20.76 MB, done
Downloading registry.npmjs.org/@next/swc-darwin-x64/14.1.0: 35.36 MB/35.36 MB, done
Downloading registry.npmjs.org/typescript/3.9.10: 9.58 MB/9.58 MB, done
Downloading registry.npmjs.org/@tabler/icons/2.47.0: 5.57 MB/5.57 MB, done
Downloading registry.npmjs.org/@biomejs/cli-darwin-x64/1.5.3: 7.16 MB/7.16 MB, done
Downloading registry.npmjs.org/turbo-darwin-64/1.12.2: 8.76 MB/8.76 MB, done
Progress: resolved 2624, reused 713, downloaded 1904, added 2624, done
node_modules/.pnpm/keccak@3.0.4/node_modules/keccak: Running install script, done in 946ms
node_modules/.pnpm/secp256k1@4.0.3/node_modules/secp256k1: Running install script, done in 1s
node_modules/.pnpm/bufferutil@4.0.8/node_modules/bufferutil: Running install script, done in 818ms
node_modules/.pnpm/utf-8-validate@5.0.10/node_modules/utf-8-validate: Running install script, done in 1.1s
node_modules/.pnpm/@fuel-ts+fuel-core@0.74.0/node_modules/@fuel-ts/fuel-core: Running install script, done in 1.9s
node_modules/.pnpm/@fuel-ts+forc@0.74.0/node_modules/@fuel-ts/forc: Running install script, done in 9.1s
node_modules/.pnpm/classic-level@1.4.1/node_modules/classic-level: Running install script, done in 831ms
node_modules/.pnpm/core-js-pure@3.35.1/node_modules/core-js-pure: Running postinstall script, done in 136ms
node_modules/.pnpm/sharp@0.32.6/node_modules/sharp: Running install script, done in 8.6s
node_modules/.pnpm/bigint-buffer@1.1.5/node_modules/bigint-buffer: Running install script, done in 8.6s
node_modules/.pnpm/@prisma+engines@5.9.1/node_modules/@prisma/engines: Running postinstall script, done in 1.8s
node_modules/.pnpm/@fuel-ts+fuel-core@0.55.0/node_modules/@fuel-ts/fuel-core: Running install script, done in 2.4s
node_modules/.pnpm/@swc+core@1.4.0/node_modules/@swc/core: Running postinstall script, done in 827ms
node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild: Running postinstall script, done in 1.1s
node_modules/.pnpm/esbuild@0.20.0/node_modules/esbuild: Running postinstall script, done in 1.5s
node_modules/.pnpm/@biomejs+biome@1.5.3/node_modules/@biomejs/biome: Running postinstall script, done in 123ms
node_modules/.pnpm/prisma@5.9.1/node_modules/prisma: Running preinstall script, done in 137ms
node_modules/.pnpm/@prisma+client@5.1.1_prisma@5.9.1/node_modules/@prisma/client: Running postinstall script, done in 1.4s

dependencies:
+ @fuels/jest 0.1.5
+ @fuels/ts-config 0.1.5
+ ethers 5.7.2
+ fuels 0.74.0
+ jest 29.7.0
+ lint-staged 15.2.2

devDependencies:
+ @babel/core 7.23.9
+ @biomejs/biome 1.5.3
+ @fuels/tsup-config 0.1.5
+ @jest/types 29.6.3
+ @next/eslint-plugin-next 14.1.0
+ @nomiclabs/hardhat-etherscan 3.1.8
+ @openzeppelin/hardhat-upgrades 3.0.2
+ @playwright/test 1.41.2
+ @swc/core 1.4.0
+ @swc/jest 0.2.36
+ @types/jest 29.5.12
+ @types/node 20.11.16
+ @types/react 18.2.54
+ @types/react-dom 18.2.18
+ @typescript-eslint/eslint-plugin 6.21.0
+ @typescript-eslint/parser 6.21.0
+ @xstate/cli 0.5.17
+ dotenv 16.4.1
+ get-tsconfig 4.7.2
+ hardhat-typechain 0.3.5
+ husky 9.0.10
+ jest-environment-jsdom 29.7.0
+ jest-transform-stub 2.0.0
+ next 14.1.0
+ npm-run-all 4.1.5
+ ts-jest 29.1.2
+ ts-node 10.9.2
+ tsup 8.0.1
+ tsx 4.7.0
+ turbo 1.12.2
+ typescript 5.3.3
+ updates 15.1.1

. prepare$ husky install
│ install command is deprecated
└─ Done in 304ms
packages/graphql prepare$ pnpm build
│ > @fuel-explorer/graphql@1.0.0 build /Users/andyfuel/dev/HoTcustemers/fuel/fuel-explorer/packages/graphql
│ > run-s codegen:fuel build:lib
│ > @fuel-explorer/graphql@1.0.0 codegen:fuel /Users/andyfuel/dev/HoTcustemers/fuel/fuel-explorer/packages/graphql
│ > gql-gen -r dotenv/config --config codegen.fuel.ts
│ TypeError: Cannot destructure property 'providerUrl' of '_fuel.FUEL_CHAIN' as it is undefined.
│     at /Users/andyfuel/dev/HoTcustemers/fuel/fuel-explorer/packages/graphql/codegen.fuel.ts:5:9
│     at evalModule (/Users/andyfuel/dev/HoTcustemers/fuel/fuel-explorer/node_modules/.pnpm/jiti@1.21.0/node_modules/jiti/dist/jiti.js:1:256443)
│     at jiti (/Users/andyfuel/dev/HoTcustemers/fuel/fuel-explorer/node_modules/.pnpm/jiti@1.21.0/node_modules/jiti/dist/jiti.js:1:254371)
│     at loadTypeScript (/Users/andyfuel/dev/HoTcustemers/fuel/fuel-explorer/node_modules/.pnpm/graphql-config@5.0.3_@types+node@20.11.16_graphql@16.8.1_typescrip…
│     at #loadConfiguration (/Users/andyfuel/dev/HoTcustemers/fuel/fuel-explorer/node_modules/.pnpm/cosmiconfig@8.3.6_typescript@5.3.3/node_modules/cosmiconfig/di…
│     at #readConfiguration (/Users/andyfuel/dev/HoTcustemers/fuel/fuel-explorer/node_modules/.pnpm/cosmiconfig@8.3.6_typescript@5.3.3/node_modules/cosmiconfig/di…
│     at async load (/Users/andyfuel/dev/HoTcustemers/fuel/fuel-explorer/node_modules/.pnpm/cosmiconfig@8.3.6_typescript@5.3.3/node_modules/cosmiconfig/dist/Explo…
│     at async Explorer.load (/Users/andyfuel/dev/HoTcustemers/fuel/fuel-explorer/node_modules/.pnpm/cosmiconfig@8.3.6_typescript@5.3.3/node_modules/cosmiconfig/d…
│     at async getConfig (/Users/andyfuel/dev/HoTcustemers/fuel/fuel-explorer/node_modules/.pnpm/graphql-config@5.0.3_@types+node@20.11.16_graphql@16.8.1_typescri…
│     at async loadConfig (/Users/andyfuel/dev/HoTcustemers/fuel/fuel-explorer/node_modules/.pnpm/graphql-config@5.0.3_@types+node@20.11.16_graphql@16.8.1_typescr…
│     at async findAndLoadGraphQLConfig (/Users/andyfuel/dev/HoTcustemers/fuel/fuel-explorer/node_modules/.pnpm/@graphql-codegen+cli@5.0.1_@parcel+watcher@2.4.0_@…
│     at async loadContext (/Users/andyfuel/dev/HoTcustemers/fuel/fuel-explorer/node_modules/.pnpm/@graphql-codegen+cli@5.0.1_@parcel+watcher@2.4.0_@types+node@20…
│     at async createContext (/Users/andyfuel/dev/HoTcustemers/fuel/fuel-explorer/node_modules/.pnpm/@graphql-codegen+cli@5.0.1_@parcel+watcher@2.4.0_@types+node@…
│     at async runCli (/Users/andyfuel/dev/HoTcustemers/fuel/fuel-explorer/node_modules/.pnpm/@graphql-codegen+cli@5.0.1_@parcel+watcher@2.4.0_@types+node@20.11.1…
│   filepath: '/Users/andyfuel/dev/HoTcustemers/fuel/fuel-explorer/packages/graphql/codegen.fuel.ts'
│ }
│  ELIFECYCLE  Command failed with exit code 1.
│ ERROR: "codegen:fuel" exited with 1.
│  ELIFECYCLE  Command failed with exit code 1.
└─ Failed in 6.1s at /Users/andyfuel/dev/HoTcustemers/fuel/fuel-explorer/packages/graphql
 ELIFECYCLE  Command failed with exit code 1.
```

When going through the guides, the expectation should be that we don't encounter these errors once we make sure we have the correct dependencies etc.  It might also be worth having the guides cover different OSes, so different sections for Windows, Mac, Linux.

Please let me know if you need additional information.

**Comment by HoTandy** [comment]
Here it just looks like we need to fix the documentation.  We need an additional step to say that the user needs 2 `.env` files in the file structure, they should be copied from the corresponding `.env.example` files in the same folder.  So copy:

`fuel-explorer/packages/app-explorer/.env.example` -> `fuel-explorer/packages/app-explorer/.env`
`fuel-explorer/packages/graphql/.env.example` -> `fuel-explorer/packages/graphql/.env`
